Bugfix cisonew
NorESMhub/BLOM pull request #92
Opened 2021-05-10 09:33 UTC by TomasTorsvik

Some bugs appeared when I set the 'cisonew' CPP flag TRUE. These bug fixes makes it possible to compile the code.

I have not done a test run with this code yet. Do we have a testcase that I can compare with?

2021-05-10 11:41 UTC, JorgSchwinger commented on hamocc/beleg_vars.F90
> +      REAL :: rco213,rco214,beta13,beta14
This bug was introduced when splitting beleg.F90 into beleg_vars.F90 and beleg_parm.F90. The variables rco213,rco214 are only used in the latter, but are still defined in the former. So they could be removed from beleg_parm.F90.

2021-05-10 11:43 UTC, JorgSchwinger requested changes
Would be great if you could also remove rco213 and rco214 from beleg_parm.F90, where they are actually not used. Otherwise it looks fine.

2021-05-10 11:51 UTC, JorgSchwinger commented
Regarding a test case, if the model is still bit-identical with the CMIP6 version, you could compare with this output 

/projects/NS2980K/schwinger/NOINYOC_T62_tn21_27_betzy

This was produce using 
create_newcase --case NOINYOC_T62_tn21_27_betzy --res T62_tn21 --mach betzy --compset NOINYOC --project nn9560k

2021-05-10 21:09 UTC, JorgSchwinger approved these changes

2021-05-13 22:22 UTC, TomasTorsvik commented
@JorgSchwinger 
NOINYOC_T62_tn21 with default settings is unchanged from the reference. When I set HAMOCC_CISO=TRUE I get an error message during build:
INIC13: Undefined variable

I guess this has something to do with missing input files? Should I merge this anyway, or is there a simple fix to get the test running?

2021-05-18 06:13 UTC, JorgSchwinger commented
Hi @TomasTorsvik 

it is simple to fix (it is a typo in the buildnml script in cime_config):

at the very end in the two lines

inic13_file = `echo $INIC13 | tr -d '"' | tr -d "'"`
inic14_file = `echo $INIC14 | tr -d '"' | tr -d "'"`


INIC13 and INIC14 have to be replaced by INID13C and INID14C (INIC13 and INIC14 are indeed never defined). Would be great if you could add this to this commit.

2021-05-18 09:37 UTC, TomasTorsvik commented
Fixed namelist variables. Now the model runs with HMAOCC_CISO=TRUE.

2021-05-18 09:37 UTC, merged